module.exports = [
  {
    title: 'The Avengers: Infinity War',
    year: 2018,
    rated: 'PG-13',
    type: 'movie',
  },
  {
    title: 'Deadpool 2',
    year: 2018,
    rated: 'R',
    type: 'movie',
  },
  {
    title: 'Thor: Ragnarok',
    year: 2017,
    rated: 'PG-13',
    type: 'movie',
  },
  {
    title: 'Black Panther',
    year: 2018,
    rated: 'PG-13',
    type: 'movie',
  },
  {
    title: 'Solo: A Star Wars Story',
    year: 2018,
    rated: 'PG-13',
    type: 'movie',
  },
  {
    title: 'A Million Ways to Die in the West',
    year: 2014,
    rated: 'R',
    runtime: 116,
    countries: [
      'USA',
    ],
    genres: [
      'Comedy',
      'Western',
    ],
    director: 'Seth MacFarlane',
    writers: [
      'Seth MacFarlane',
      'Alec Sulkin',
      'Wellesley Wild',
    ],
    actors: [
      'Seth MacFarlane',
      'Charlize Theron',
      'Amanda Seyfried',
      'Liam Neeson',
    ],
    plot: 'As a cowardly farmer begins to fall for the mysterious new woman in town, he must put his new-found courage to the test when her husband, a notorious gun-slinger, announces his arrival.',
    poster: 'http://ia.media-imdb.com/images/M/MV5BMTQ0NDcyNjg0MV5BMl5BanBnXkFtZTgwMzk4NTA4MTE@._V1_SX300.jpg',
    imdb: {
      id: 'tt2557490',
      rating: 6.1,
      votes: 126592,
    },
    tomato: {
      meter: 33,
      image: 'rotten',
      rating: 4.9,
      reviews: 188,
      fresh: 62,
      consensus: 'While it offers a few laughs and boasts a talented cast, Seth MacFarlane\'s overlong, aimless A Million Ways to Die in the West is a disappointingly scattershot affair.',
      userMeter: 40,
      userRating: 3,
      userReviews: 62945,
    },
    metacritic: 44,
    awards: {
      wins: 0,
      nominations: 6,
      text: '6 nominations.',
    },
    type: 'movie',
  },
  {
    title: 'Wild Wild West',
    year: 1999,
    rated: 'PG-13',
    runtime: 106,
    countries: [
      'USA',
    ],
    genres: [
      'Action',
      'Western',
      'Comedy',
    ],
    director: 'Barry Sonnenfeld',
    writers: [
      'Jim Thomas',
      'John Thomas',
      'S.S. Wilson',
      'Brent Maddock',
      'Jeffrey Price',
      'Peter S. Seaman',
    ],
    actors: [
      'Will Smith',
      'Kevin Kline',
      'Kenneth Branagh',
      'Salma Hayek',
    ],
    plot: 'The two best hired guns in the West must save President Grant from the clutches of a nineteenth-century inventor-villain.',
    poster: 'http://ia.media-imdb.com/images/M/MV5BNDI5NDk5MjgxMl5BMl5BanBnXkFtZTcwNjI1MTUyMQ@@._V1_SX300.jpg',
    imdb: {
      id: 'tt0120891',
      rating: 4.8,
      votes: 124558,
    },
    tomato: {
      meter: 17,
      image: 'rotten',
      rating: 4.1,
      reviews: 130,
      fresh: 22,
      consensus: 'Bombastic, manic, and largely laugh-free, Wild Wild West is a bizarre misfire in which greater care was lavished upon the special effects than on the script.',
      userMeter: 28,
      userRating: 2.7,
      userReviews: 463740,
    },
    metacritic: 38,
    awards: {
      wins: 10,
      nominations: 11,
      text: '10 wins & 11 nominations.',
    },
    type: 'movie',
  },
  {
    title: 'West Side Story',
    year: 1961,
    rated: 'UNRATED',
    runtime: 152,
    countries: [
      'USA',
    ],
    genres: [
      'Crime',
      'Drama',
      'Musical',
    ],
    director: 'Jerome Robbins, Robert Wise',
    writers: [
      'Ernest Lehman',
      'Arthur Laurents',
      'Jerome Robbins',
    ],
    actors: [
      'Natalie Wood',
      'Richard Beymer',
      'Russ Tamblyn',
      'Rita Moreno',
    ],
    plot: 'Two youngsters from rival New York City gangs fall in love, but tensions between their respective friends build toward tragedy.',
    poster: 'http://ia.media-imdb.com/images/M/MV5BMTM0NDAxOTI5MF5BMl5BanBnXkFtZTcwNjI4Mjg3NA@@._V1_SX300.jpg',
    imdb: {
      id: 'tt0055614',
      rating: 7.6,
      votes: 67824,
    },
    awards: {
      wins: 18,
      nominations: 11,
      text: 'Won 10 Oscars. Another 18 wins & 11 nominations.',
    },
    type: 'movie',
  },
  {
    title: 'Slow West',
    year: 2015,
    rated: 'R',
    runtime: 84,
    countries: [
      'UK',
      'New Zealand',
    ],
    genres: [
      'Action',
      'Thriller',
      'Western',
    ],
    director: 'John Maclean',
    writers: [
      'John Maclean',
    ],
    actors: [
      'Kodi Smit-McPhee',
      'Michael Fassbender',
      'Ben Mendelsohn',
      'Aorere Paki',
    ],
    plot: 'A young Scottish man travels across America in pursuit of the woman he loves, attracting the attention of an outlaw who is willing to serve as a guide.',
    poster: 'http://ia.media-imdb.com/images/M/MV5BNTYxNDA5ODk5NF5BMl5BanBnXkFtZTgwNzMwMzIwNTE@._V1_SX300.jpg',
    imdb: {
      id: 'tt3205376',
      rating: 7,
      votes: 19101,
    },
    tomato: {
      meter: 95,
      image: 'certified',
      rating: 7.5,
      reviews: 115,
      fresh: 106,
      consensus: 'Slow West serves as an impressive calling card for first-time writer-director John M. Maclean -- and offers an inventive treat for fans of the Western.',
      userMeter: 75,
      userRating: 3.7,
      userReviews: 9850,
    },
    metacritic: 72,
    awards: {
      wins: 2,
      nominations: 9,
      text: '2 wins & 9 nominations.',
    },
    type: 'movie',
  },
  {
    title: 'An American Tail: Fievel Goes West',
    year: 1991,
    rated: 'G',
    runtime: 75,
    countries: [
      'USA',
    ],
    genres: [
      'Animation',
      'Adventure',
      'Family',
    ],
    director: 'Phil Nibbelink, Simon Wells',
    writers: [
      'Flint Dille',
      'Charles Swenson',
      'David Kirschner',
    ],
    actors: [
      'Phillip Glasser',
      'James Stewart',
      'Erica Yohn',
      'Cathy Cavadini',
    ],
    plot: 'A family of Emigre mice decide to move out to the west, unaware that they are falling into a trap perpetrated by a smooth talking cat.',
    poster: 'http://ia.media-imdb.com/images/M/MV5BMTYzODMxNTUyNF5BMl5BanBnXkFtZTcwMTAwMzQyMQ@@._V1_SX300.jpg',
    imdb: {
      id: 'tt0101329',
      rating: 6.4,
      votes: 16013,
    },
    awards: {
      wins: 0,
      nominations: 0,
      text: '',
    },
    type: 'movie',
  },
  {
    title: 'Red Rock West',
    year: 1993,
    rated: 'R',
    runtime: 98,
    countries: [
      'USA',
    ],
    genres: [
      'Crime',
      'Drama',
      'Thriller',
    ],
    director: 'John Dahl',
    writers: [
      'John Dahl',
      'Rick Dahl',
    ],
    actors: [
      'Nicolas Cage',
      'Dennis Hopper',
      'Lara Flynn Boyle',
      'J.T. Walsh',
    ],
    plot: 'When a promised job for Texan Michael fails to materialise in Wyoming, Mike is mistaken by Wayne to be the hitman he hired to kill his unfaithful wife, Suzanne. Mike takes full advantage of...',
    poster: 'http://ia.media-imdb.com/images/M/MV5BMTk0Mjg4OTc3OF5BMl5BanBnXkFtZTYwNzgzOTg5._V1_SX300.jpg',
    imdb: {
      id: 'tt0105226',
      rating: 7,
      votes: 15007,
    },
    awards: {
      wins: 0,
      nominations: 3,
      text: '3 nominations.',
    },
    type: 'movie',
  },
  {
    title: 'How the West Was Won',
    year: 1962,
    rated: 'APPROVED',
    runtime: 164,
    countries: [
      'USA',
    ],
    genres: [
      'Western',
    ],
    director: 'John Ford, Henry Hathaway, George Marshall, Richard Thorpe',
    writers: [
      'James R. Webb',
    ],
    actors: [
      'Carroll Baker',
      'Lee J. Cobb',
      'Henry Fonda',
      'Carolyn Jones',
    ],
    plot: 'A family saga covering several decades of Westward expansion in the nineteenth century--including the Gold Rush, the Civil War, and the building of the railroads.',
    poster: 'http://ia.media-imdb.com/images/M/MV5BNTk2NDk1NjY0MV5BMl5BanBnXkFtZTgwMzkzNTcxMTE@._V1_SX300.jpg',
    imdb: {
      id: 'tt0056085',
      rating: 7.5,
      votes: 13640,
    },
    awards: {
      wins: 7,
      nominations: 5,
      text: 'Won 3 Oscars. Another 7 wins & 5 nominations.',
    },
    type: 'movie',
  },
  {
    title: 'Journey to the West',
    year: 2013,
    rated: 'PG-13',
    runtime: 110,
    countries: [
      'China',
    ],
    genres: [
      'Adventure',
      'Comedy',
      'Fantasy',
    ],
    director: 'Stephen Chow, Chi-kin Kwok',
    writers: [
      'Stephen Chow',
      'Chi-kin Kwok',
      'Xin Huo',
      'Yun Wang',
      'Chi Keung Fung',
      'Zhengyu Lu',
      'Shing-Cheung Lee',
      'Ivy Kong',
    ],
    actors: [
      'Qi Shu',
      'Zhang Wen',
      'Bo Huang',
      'Show Luo',
    ],
    plot: 'Tang Sanzang, an aspiring Buddhist hero tries to protect a village from three demons. He develops complex feelings for Miss Duan, the demon hunter who repeatedly helps him, and finally quests to meet the legendary Monkey King.',
    poster: 'http://ia.media-imdb.com/images/M/MV5BMTQzMzUxNzk0NV5BMl5BanBnXkFtZTgwMTEwOTE4MDE@._V1_SX300.jpg',
    imdb: {
      id: 'tt2017561',
      rating: 6.8,
      votes: 7111,
    },
    tomato: {
      meter: 93,
      image: 'fresh',
      rating: 7.2,
      reviews: 30,
      fresh: 28,
      consensus: 'As sweet, silly, action-packed and ridiculous as director Steven Chow\'s best work, Journey to the West serves up dazzling action sequences while playing its disparate elements against each other with thrilling abandon.',
      userMeter: 68,
      userRating: 3.6,
      userReviews: 2198,
    },
    metacritic: 68,
    awards: {
      wins: 1,
      nominations: 12,
      text: '1 win & 12 nominations.',
    },
    type: 'movie',
  },
  {
    title: 'West of Memphis',
    year: 2012,
    rated: 'R',
    runtime: 147,
    countries: [
      'New Zealand',
      'USA',
    ],
    genres: [
      'Documentary',
    ],
    director: 'Amy Berg',
    writers: [
      'Amy Berg',
      'Billy McMillin',
    ],
    actors: [
      'Michael Baden',
      'Jason Baldwin',
      'Holly Ballard',
      'Jamie Clark Ballard',
    ],
    plot: 'An examination of a failure of justice in the case against the West Memphis Three.',
    poster: 'http://ia.media-imdb.com/images/M/MV5BMjIzNDM3NjkzOV5BMl5BanBnXkFtZTcwNjI5Nzg0OA@@._V1_SX300.jpg',
    imdb: {
      id: 'tt2130321',
      rating: 7.9,
      votes: 6627,
    },
    tomato: {
      meter: 95,
      image: 'certified',
      rating: 7.9,
      reviews: 111,
      fresh: 106,
      consensus: 'Both a sobering look at a true crime story and a scathing indictment of the American justice system, West of Memphis is a real-life horror story told with fury and compassion.',
      userMeter: 87,
      userRating: 4.1,
      userReviews: 8482,
    },
    metacritic: 80,
    awards: {
      wins: 0,
      nominations: 9,
      text: 'Nominated for 1 BAFTA Film Award. Another 9 nominations.',
    },
    type: 'movie',
  },
  {
    title: 'Star Wars: Episode IV - A New Hope',
    year: 1977,
    rated: 'PG',
    runtime: 121,
    countries: [
      'USA',
    ],
    genres: [
      'Action',
      'Adventure',
      'Fantasy',
    ],
    director: 'George Lucas',
    writers: [
      'George Lucas',
    ],
    actors: [
      'Mark Hamill',
      'Harrison Ford',
      'Carrie Fisher',
      'Peter Cushing',
    ],
    plot: 'Luke Skywalker joins forces with a Jedi Knight, a cocky pilot, a wookiee and two droids to save the universe from the Empire\'s world-destroying battle-station, while also attempting to rescue Princess Leia from the evil Darth Vader.',
    poster: 'http://ia.media-imdb.com/images/M/MV5BMTU4NTczODkwM15BMl5BanBnXkFtZTcwMzEyMTIyMw@@._V1_SX300.jpg',
    imdb: {
      id: 'tt0076759',
      rating: 8.7,
      votes: 822849,
    },
    tomato: {
      meter: 94,
      image: 'certified',
      rating: 8.5,
      reviews: 99,
      fresh: 93,
      consensus: 'A legendarily expansive and ambitious start to the sci-fi saga, George Lucas opened our eyes to the possibilities of blockbuster filmmaking and things have never been the same.',
      userMeter: 96,
      userRating: 4.1,
      userReviews: 851120,
    },
    metacritic: 92,
    awards: {
      wins: 38,
      nominations: 27,
      text: 'Won 6 Oscars. Another 38 wins & 27 nominations.',
    },
    type: 'movie',
  },
  {
    title: 'Star Wars: Episode V - The Empire Strikes Back',
    year: 1980,
    rated: 'PG',
    runtime: 124,
    countries: [
      'USA',
    ],
    genres: [
      'Action',
      'Adventure',
      'Fantasy',
    ],
    director: 'Irvin Kershner',
    writers: [
      'Leigh Brackett',
      'Lawrence Kasdan',
      'George Lucas',
    ],
    actors: [
      'Mark Hamill',
      'Harrison Ford',
      'Carrie Fisher',
      'Billy Dee Williams',
    ],
    plot: 'After the rebels have been brutally overpowered by the Empire on their newly established base, Luke Skywalker takes advanced Jedi training with Master Yoda, while his friends are pursued by Darth Vader as part of his plan to capture Luke.',
    poster: 'http://ia.media-imdb.com/images/M/MV5BMjE2MzQwMTgxN15BMl5BanBnXkFtZTcwMDQzNjk2OQ@@._V1_SX300.jpg',
    imdb: {
      id: 'tt0080684',
      rating: 8.8,
      votes: 739949,
    },
    tomato: {
      meter: 94,
      image: 'certified',
      rating: 8.9,
      reviews: 87,
      fresh: 82,
      consensus: 'Dark, sinister, but ultimately even more involving than A New Hope, The Empire Strikes Back defies viewer expectations and takes the series to heightened emotional levels.',
      userMeter: 97,
      userRating: 4.1,
      userReviews: 1045537,
    },
    metacritic: 79,
    awards: {
      wins: 15,
      nominations: 17,
      text: 'Won 1 Oscar. Another 15 wins & 17 nominations.',
    },
    type: 'movie',
  },
  {
    title: 'Star Wars: Episode VI - Return of the Jedi',
    year: 1983,
    rated: 'PG',
    runtime: 131,
    countries: [
      'USA',
    ],
    genres: [
      'Action',
      'Adventure',
      'Fantasy',
    ],
    director: 'Richard Marquand',
    writers: [
      'Lawrence Kasdan',
      'George Lucas',
      'George Lucas',
    ],
    actors: [
      'Mark Hamill',
      'Harrison Ford',
      'Carrie Fisher',
      'Billy Dee Williams',
    ],
    plot: 'After rescuing Han Solo from the palace of Jabba the Hutt, the rebels attempt to destroy the second Death Star, while Luke struggles to make Vader return from the dark side of the Force.',
    poster: 'http://ia.media-imdb.com/images/M/MV5BMTQ0MzI1NjYwOF5BMl5BanBnXkFtZTgwODU3NDU2MTE@._V1._CR93,97,1209,1861_SX89_AL_.jpg_V1_SX300.jpg',
    imdb: {
      id: 'tt0086190',
      rating: 8.4,
      votes: 623252,
    },
    tomato: {
      meter: 80,
      image: 'certified',
      rating: 7.2,
      reviews: 84,
      fresh: 67,
      consensus: 'Though failing to reach the cinematic heights of its predecessors, Return of the Jedi remains an entertaining sci-fi adventure and a fitting end to the classic trilogy.',
      userMeter: 94,
      userRating: 4,
      userReviews: 1003937,
    },
    metacritic: 52,
    awards: {
      wins: 15,
      nominations: 15,
      text: 'Nominated for 4 Oscars. Another 15 wins & 15 nominations.',
    },
    type: 'movie',
  },
  {
    title: 'Star Wars: Episode I - The Phantom Menace',
    year: 1999,
    rated: 'PG',
    runtime: 136,
    countries: [
      'USA',
    ],
    genres: [
      'Action',
      'Adventure',
      'Fantasy',
    ],
    director: 'George Lucas',
    writers: [
      'George Lucas',
    ],
    actors: [
      'Liam Neeson',
      'Ewan McGregor',
      'Natalie Portman',
      'Jake Lloyd',
    ],
    plot: 'Two Jedi Knights escape a hostile blockade to find allies and come across a young boy who may bring balance to the Force, but the long dormant Sith resurface to reclaim their old glory.',
    poster: 'http://ia.media-imdb.com/images/M/MV5BMTQ4NjEwNDA2Nl5BMl5BanBnXkFtZTcwNDUyNDQzNw@@._V1_SX300.jpg',
    imdb: {
      id: 'tt0120915',
      rating: 6.5,
      votes: 494267,
    },
    tomato: null,
    metacritic: 51,
    awards: {
      wins: 17,
      nominations: 59,
      text: 'Nominated for 3 Oscars. Another 17 wins & 59 nominations.',
    },
    type: 'movie',
  },
  {
    title: 'Star Wars: Episode III - Revenge of the Sith',
    year: 2005,
    rated: 'PG-13',
    runtime: 140,
    countries: [
      'USA',
    ],
    genres: [
      'Action',
      'Adventure',
      'Fantasy',
    ],
    director: 'George Lucas',
    writers: [
      'George Lucas',
    ],
    actors: [
      'Ewan McGregor',
      'Natalie Portman',
      'Hayden Christensen',
      'Ian McDiarmid',
    ],
    plot: 'Three years after the onset of the Clone Wars; the noble Jedi Knights are spread out across the galaxy leading a massive clone army in the war against the Separatists. After Chancellor ...',
    poster: 'http://ia.media-imdb.com/images/M/MV5BNTc4MTc3NTQ5OF5BMl5BanBnXkFtZTcwOTg0NjI4NA@@._V1_SX300.jpg',
    imdb: {
      id: 'tt0121766',
      rating: 7.6,
      votes: 483613,
    },
    tomato: {
      meter: 79,
      image: 'certified',
      rating: 7.3,
      reviews: 282,
      fresh: 222,
      consensus: 'With Episode III: Revenge of the Sith, George Lucas brings his second Star Wars trilogy to a suitably thrilling and often poignant -- if still a bit uneven -- conclusion.',
      userMeter: 65,
      userRating: 3.1,
      userReviews: 33674396,
    },
    metacritic: 68,
    awards: {
      wins: 21,
      nominations: 49,
      text: 'Nominated for 1 Oscar. Another 21 wins & 49 nominations.',
    },
    type: 'movie',
  },
  {
    title: 'Star Trek',
    year: 2009,
    rated: 'PG-13',
    runtime: 127,
    countries: [
      'USA',
      'Germany',
    ],
    genres: [
      'Action',
      'Adventure',
      'Sci-Fi',
    ],
    director: 'J.J. Abrams',
    writers: [
      'Roberto Orci',
      'Alex Kurtzman',
      'Gene Roddenberry',
    ],
    actors: [
      'Chris Pine',
      'Zachary Quinto',
      'Leonard Nimoy',
      'Eric Bana',
    ],
    plot: 'The brash James T. Kirk tries to live up to his father\'s legacy with Mr. Spock keeping him in check as a vengeful, time-traveling Romulan creates black holes to destroy the Federation one planet at a time.',
    poster: 'http://ia.media-imdb.com/images/M/MV5BMjE5NDQ5OTE4Ml5BMl5BanBnXkFtZTcwOTE3NDIzMw@@._V1_SX300.jpg',
    imdb: {
      id: 'tt0796366',
      rating: 8,
      votes: 483229,
    },
    tomato: {
      meter: 95,
      image: 'certified',
      rating: 8.2,
      reviews: 340,
      fresh: 312,
      consensus: 'Star Trek reignites a classic franchise with action, humor, a strong story, and brilliant visuals, and will please traditional Trekkies and new fans alike.',
      userMeter: 91,
      userRating: 4.1,
      userReviews: 743375,
    },
    metacritic: 82,
    awards: {
      wins: 22,
      nominations: 77,
      text: 'Won 1 Oscar. Another 22 wins & 77 nominations.',
    },
    type: 'movie',
  },
  {
    title: 'Star Wars: Episode II - Attack of the Clones',
    year: 2002,
    rated: 'PG',
    runtime: 142,
    countries: [
      'USA',
    ],
    genres: [
      'Action',
      'Adventure',
      'Fantasy',
    ],
    director: 'George Lucas',
    writers: [
      'George Lucas',
      'Jonathan Hales',
      'George Lucas',
    ],
    actors: [
      'Ewan McGregor',
      'Natalie Portman',
      'Hayden Christensen',
      'Christopher Lee',
    ],
    plot: 'Ten years after initially meeting, Anakin Skywalker shares a forbidden romance with Padmé, while Obi-Wan investigates an assassination attempt on the Senator and discovers a secret clone army crafted for the Jedi.',
    poster: 'http://ia.media-imdb.com/images/M/MV5BMTY5MjI5NTIwNl5BMl5BanBnXkFtZTYwMTM1Njg2._V1_SX300.jpg',
    imdb: {
      id: 'tt0121765',
      rating: 6.7,
      votes: 425728,
    },
    tomato: {
      meter: 66,
      image: 'fresh',
      rating: 6.7,
      reviews: 242,
      fresh: 159,
      consensus: 'Star Wars Episode II: Attack of the Clones benefits from an increased emphasis on thrilling action, although they\'re once again undercut by ponderous plot points and underdeveloped characters.',
      userMeter: 58,
      userRating: 3.3,
      userReviews: 844634,
    },
    metacritic: 54,
    awards: {
      wins: 13,
      nominations: 47,
      text: 'Nominated for 1 Oscar. Another 13 wins & 47 nominations.',
    },
    type: 'movie',
  },
  {
    title: 'Star Trek Into Darkness',
    year: 2013,
    rated: 'PG-13',
    runtime: 132,
    countries: [
      'USA',
    ],
    genres: [
      'Action',
      'Adventure',
      'Sci-Fi',
    ],
    director: 'J.J. Abrams',
    writers: [
      'Roberto Orci',
      'Alex Kurtzman',
      'Damon Lindelof',
      'Gene Roddenberry',
    ],
    actors: [
      'Chris Pine',
      'Zachary Quinto',
      'Zoe Saldana',
      'Karl Urban',
    ],
    plot: 'After the crew of the Enterprise find an unstoppable force of terror from within their own organization, Captain Kirk leads a manhunt to a war-zone world to capture a one-man weapon of mass destruction.',
    poster: 'http://ia.media-imdb.com/images/M/MV5BMTk2NzczOTgxNF5BMl5BanBnXkFtZTcwODQ5ODczOQ@@._V1_SX300.jpg',
    imdb: {
      id: 'tt1408101',
      rating: 7.8,
      votes: 370638,
    },
    tomato: {
      meter: 87,
      image: 'certified',
      rating: 7.6,
      reviews: 250,
      fresh: 217,
      consensus: 'Visually spectacular and suitably action packed, Star Trek Into Darkness is a rock-solid installment in the venerable sci-fi franchise, even if it\'s not as fresh as its predecessor.',
      userMeter: 90,
      userRating: 4.2,
      userReviews: 309531,
    },
    metacritic: 72,
    awards: {
      wins: 6,
      nominations: 44,
      text: 'Nominated for 1 Oscar. Another 6 wins & 44 nominations.',
    },
    type: 'movie',
  },
  {
    title: 'Star Trek: First Contact',
    year: 1996,
    rated: 'PG-13',
    runtime: 111,
    countries: [
      'USA',
    ],
    genres: [
      'Action',
      'Adventure',
      'Sci-Fi',
    ],
    director: 'Jonathan Frakes',
    writers: [
      'Gene Roddenberry',
      'Rick Berman',
      'Brannon Braga',
      'Ronald D. Moore',
      'Brannon Braga',
      'Ronald D. Moore',
    ],
    actors: [
      'Patrick Stewart',
      'Jonathan Frakes',
      'Brent Spiner',
      'LeVar Burton',
    ],
    plot: 'The Borg go back in time intent on preventing Earth\'s first contact with an alien species. Captain Picard and his crew pursue them to ensure that Zefram Cochrane makes his maiden flight reaching warp speed.',
    poster: 'http://ia.media-imdb.com/images/M/MV5BMTg4OTYwODY4MF5BMl5BanBnXkFtZTgwNTg2NjIyMDE@._V1_SX300.jpg',
    imdb: {
      id: 'tt0117731',
      rating: 7.6,
      votes: 94153,
    },
    tomato: {
      meter: 93,
      image: 'certified',
      rating: 7.4,
      reviews: 55,
      fresh: 51,
      consensus: 'While fans of the series will surely appreciate it, First Contact is exciting, engaging, and visually appealing enough to entertain Star Trek novices.',
      userMeter: 89,
      userRating: 3.6,
      userReviews: 99646,
    },
    metacritic: 71,
    awards: {
      wins: 8,
      nominations: 19,
      text: 'Nominated for 1 Oscar. Another 8 wins & 19 nominations.',
    },
    type: 'movie',
  },
  {
    title: 'Star Trek II: The Wrath of Khan',
    year: 1982,
    rated: 'PG',
    runtime: 113,
    countries: [
      'USA',
    ],
    genres: [
      'Action',
      'Adventure',
      'Drama',
    ],
    director: 'Nicholas Meyer',
    writers: [
      'Gene Roddenberry',
      'Harve Bennett',
      'Jack B. Sowards',
      'Jack B. Sowards',
    ],
    actors: [
      'William Shatner',
      'Leonard Nimoy',
      'DeForest Kelley',
      'James Doohan',
    ],
    plot: 'With the assistance of the Enterprise crew, Admiral Kirk must stop an old nemesis, Khan Noonien Singh, from using the life-generating Genesis Device as the ultimate weapon.',
    poster: 'http://ia.media-imdb.com/images/M/MV5BMTcwNjc5NjA4N15BMl5BanBnXkFtZTcwNDk5MzI4OA@@._V1_SX300.jpg',
    imdb: {
      id: 'tt0084726',
      rating: 7.7,
      votes: 86687,
    },
    tomato: {
      meter: 88,
      image: 'certified',
      rating: 8,
      reviews: 49,
      fresh: 43,
      consensus: 'Considered by many fans to be the best of the Star Trek movies, Khan features a strong plot, increased tension, and a sharp supporting performance from Ricardo Montalban.',
      userMeter: 90,
      userRating: 3.8,
      userReviews: 84279,
    },
    metacritic: 71,
    awards: {
      wins: 2,
      nominations: 9,
      text: '2 wins & 9 nominations.',
    },
    type: 'movie',
  },
];
